name: Generate Installable Plugin, and Upload as Release Asset
on:
  release:
    types:
      - created

jobs:
  build:
    name: Build and Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build project
        run: |
          composer install --no-dev --optimize-autoloader
          mkdir build
      - name: Create artifact
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -X -r ${{ github.event.repository.name }}.zip . -x *.git* 
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.event.repository.name }}.zip
          asset_name: churchtools-wp-sync
          tag: ${{ github.ref }}
          overwrite: true
          body: "This is my release text"
#      - name: Upload artifact
#        uses: actions/upload-artifact@v2
#        with:
#            name: graphql-api
#            path: build/graphql-api.zip
#      - name: Upload to release
#        uses: JasonEtco/upload-to-release@master
#        with:
#          args: build/graphql-api.zip application/zip
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}